repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: system
    types_or: [python]
    entry: mypy
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args:
        - --fix
        - --select=F,I,ANN
    # Run the formatter.
    - id: ruff-format
